// example-apps/angular/src/app/app.component.ts
import { Component } from '@angular/core';
import clevertap from 'clevertap-web-sdk';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.sass']
})
export class AppComponent {
  title = 'clevertap-sdk-angular';

  ngOnInit () {
    clevertap.init('YOUR_ACCOUNT_ID'); // Replace YOUR_ACCOUNT_ID, can be initialized just once
  }

  handleEventPushClick () {
    clevertap.event.push('Product Viewed', {
      "Product name": "Casio Chronograph Watch",
      "Category": "Mens Accessories",
      "Price": 59.99,
      "Date": new Date()
    }); // Replace Payload as per your event schema and design
  }
}

<div>
  <h3>CleverTap Web SDK using Angular</h3>
  <div>
    <button (click)="handleEventPushClick()">Push Event</button>
  </div>
</div>

<router-outlet></router-outlet>

// example-apps/react/src/App.js
import './App.css';
import clevertap from 'clevertap-web-sdk';

function App() {
  clevertap.init('YOUR_ACCOUNT_ID'); // Replace YOUR_ACCOUNT_ID, can be initialized just once
  return (
    <div className="App">
      <h3>CleverTap Web SDK using React</h3>
      <div>
        <button onClick={handleEventPushClick}>Push Event</button>
      </div>
    </div>
  );
}

function handleEventPushClick () {
  clevertap.event.push('Product Viewed', {
    "Product name": "Casio Chronograph Watch",
    "Category": "Mens Accessories",
    "Price": 59.99,
    "Date": new Date()
  }); // Replace Payload as per your event schema and design
}

export default App;
